version: 2
jobs:
  build:
    machine:
      image: circleci/buildpack-deps:stretch
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker-compose build
