version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker-compose build
